pipeline {
    agent any
    environment {
        SOLUTION_IMAGE_NAME = "hw1-milestone1-solution:build$BUILD_NUMBER"
    }
    options {
        skipDefaultCheckout(true)
    }
    parameters {
        string(name: 'STUDENT_NAME', defaultValue: '', description: 'Name of student')
        string(name: 'GITHUB_CLONE_URL', defaultValue: '', description: 'Github repository clone URL (use SSH scheme).')
        string(name: 'GIT_COMMIT_HASH', defaultValue: '', description: 'Commit id of your solution in the repository')
    }
    stages {
        stage('Sanity check') {
            steps {
                script {
                    if (STUDENT_NAME == '' || GITHUB_CLONE_URL == '' || GIT_COMMIT_HASH == '') {
                        currentBuild.result = 'ABORTED'
                        error("Not all required parameters are specified.")
                    }
                    if (STUDENT_NAME)
                    if (!GITHUB_CLONE_URL.startsWith("git@github.com")) {
                        currentBuild.result = 'ABORTED'
                        error("GITHUB_CLONE_URL doesn't seem to use SSH scheme")
                    }
                    if (!GIT_COMMIT_HASH.matches("^[0-9a-f]{40}\$")) {
                        currentBuild.result = 'ABORTED'
                        error("GIT_COMMIT_HASH doesn't seem to be a SHA-1 hash. Please, specify full commit hash here. Don't use tags or branches")
                    }
                    cleanWs()
                    checkout scm
                    echo "Building ${env.JOB_NAME}..."
                }
            }
        }
        stage('Clone solution repository') {
            steps {
                script {
                    sh 'eval `ssh-agent -s` && ssh-add /var/lib/jenkins/.ssh/github_hse_system_design_bot2 && git clone ${GITHUB_CLONE_URL} solution'
                    sh 'cd solution && git checkout ${GIT_COMMIT_HASH} && cd ..'

                    // actually, this should never fail because github would reject an attempt to push 40-hex-long tags.
                    sh 'cd solution && [ "${GIT_COMMIT_HASH}" =  `git rev-parse HEAD` ] || (echo "GIT_COMMIT_HASH seems to be a branch or label" && false)'
                }
            }
        }
        stage('Clone baseline repository') {
            steps {
                script {
                    sh 'eval `ssh-agent -s` && ssh-add /var/lib/jenkins/.ssh/github_hse_system_design_bot2 && git clone git@github.com:hse-system-design/baseline-hw-1.git baseline'
                    sh 'cd baseline && git checkout hw1-milestone1 && cd ..'
                }
            }
        }

        stage('Build solution image') {
            steps {
                script {
                    sh 'docker build -t ${SOLUTION_IMAGE_NAME} solution'
                }
            }
        }
        stage('Run solution') {
            steps {
                script {
                    echo 'Run solution container'
                    sh 'docker run -d -e SERVER_PORT=8080 ${SOLUTION_IMAGE_NAME} >solution_container_id.txt'
                    sh "docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' `cat solution_container_id.txt` >solution_container_ip.txt"
                    echo 'Container id is `cat solution_container_id.txt`, ip is `solution_container_ip.txt`'
                }
            }
        }
        stage('Run tests') {
            steps {
                script {
                    docker.image('golang:1.19').inside("-v ${WORKSPACE}:/output") {
                        sh 'ls'
                        sh 'pwd'
                        sh 'cd baseline && GOCACHE=/tmp/.cache go mod tidy'
                        sh 'cd baseline && API_URL=http://`cat ../solution_container_ip.txt`:8080 GOCACHE=/tmp/.cache go test -v -timeout 120s ./src/apitest 2>&1 | tee /output/rawtest.txt'
                    }
                }
            }
        }
    }

    post {
        always {
            sh 'docker kill `cat solution_container_id.txt` || echo "Failed to kill solution docker container, maybe it didnt start"'

            echo 'Collecting logs from containers for debugging'
            sh 'echo "CONTAINER ==============================\n" >> logs.txt'
            sh 'docker logs `cat solution_container_id.txt` >> logs.txt 2>&1 || true'
            archiveArtifacts artifacts: 'logs.txt', fingerprint: true

            script {
                docker.image('golang:1.19').inside("-v ${WORKSPACE}:/output") {
                    sh 'GOCACHE=/tmp/.cache go install github.com/ADKosm/go-junit-report@v0.9.2'
                    sh 'cat rawtest.txt | go-junit-report > /output/junit.xml || true'
                }
            }
            junit 'junit.xml'
        }
    }
}
